# Generated by Django 5.2.6 on 2025-09-08 15:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('language', models.CharField(default='Русский', max_length=50, verbose_name='Язык')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, upload_to='book_covers/', verbose_name='Обложка')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Страниц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название филиала')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('opening_hours', models.JSONField(default=dict, verbose_name='Часы работы')),
                ('total_seats', models.IntegerField(default=0, verbose_name='Всего мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Филиал библиотеки',
                'verbose_name_plural': 'Филиалы библиотек',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('borrowed', 'Выдана'), ('reserved', 'Зарезервирована'), ('maintenance', 'На ремонте'), ('lost', 'Утеряна')], default='available', max_length=20, verbose_name='Статус')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('condition', models.CharField(default='good', max_length=50, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.book', verbose_name='Книга')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Экземпляр книги',
                'verbose_name_plural': 'Экземпляры книг',
            },
        ),
        migrations.CreateModel(
            name='BookBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Обрабатывается'), ('ready', 'Готов к выдаче'), ('issued', 'Выдан'), ('cancelled', 'Отменен'), ('expired', 'Просрочен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_by', models.DateTimeField(blank=True, null=True, verbose_name='Готов к')),
                ('pickup_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Забрать до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.bookcopy', verbose_name='Экземпляр книги')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Бронирование книги',
                'verbose_name_plural': 'Бронирования книг',
            },
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('due_date', models.DateTimeField(verbose_name='Вернуть до')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('renewals', models.IntegerField(default=0, verbose_name='Продления')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='Просрочка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.bookcopy', verbose_name='Экземпляр книги')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.bookbooking', verbose_name='Бронирование')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loans', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_loans', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выдача книги',
                'verbose_name_plural': 'Выдачи книг',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('reason', models.CharField(max_length=200, verbose_name='Причина')),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='unpaid', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.bookloan', verbose_name='Выдача книги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('guest', 'Гость'), ('reader', 'Читатель'), ('librarian', 'Библиотекарь'), ('admin', 'Администратор')], default='guest', max_length=10, verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='Факультет')),
                ('student_group', models.CharField(blank=True, max_length=50, verbose_name='Группа')),
                ('library_card', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Читательский билет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteka.publisher', verbose_name='Издательство'),
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('floor', models.IntegerField(default=1, verbose_name='Этаж')),
                ('total_seats', models.IntegerField(verbose_name='Всего мест')),
                ('available_seats', models.IntegerField(default=0, verbose_name='Доступно мест')),
                ('has_computers', models.BooleanField(default=False, verbose_name='Есть компьютеры')),
                ('has_outlets', models.BooleanField(default=False, verbose_name='Есть розетки')),
                ('opening_hours', models.JSONField(default=dict, verbose_name='Часы работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Читальный зал',
                'verbose_name_plural': 'Читальные залы',
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Номер места')),
                ('seat_type', models.CharField(choices=[('standard', 'Стандартное'), ('computer', 'Компьютерное'), ('group', 'Групповое'), ('silent', 'Тихое')], default='standard', max_length=20, verbose_name='Тип места')),
                ('has_outlet', models.BooleanField(default=False, verbose_name='Есть розетка')),
                ('has_computer', models.BooleanField(default=False, verbose_name='Есть компьютер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('x_coord', models.IntegerField(blank=True, null=True, verbose_name='Координата X')),
                ('y_coord', models.IntegerField(blank=True, null=True, verbose_name='Координата Y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.readingroom', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место в зале',
                'verbose_name_plural': 'Места в залах',
                'unique_together': {('room', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('duration', models.IntegerField(verbose_name='Длительность (часы)')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('no_show', 'Не явился')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.branch', verbose_name='Филиал')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.readingroom', verbose_name='Зал')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.roomseat', verbose_name='Место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование места',
                'verbose_name_plural': 'Бронирования мест',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.author', verbose_name='Автор')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Автор книги',
                'verbose_name_plural': 'Авторы книг',
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о книге',
                'verbose_name_plural': 'Отзывы о книгах',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция в очереди')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('notified', 'Уведомлен'), ('cancelled', 'Отменен'), ('completed', 'Завершено')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Время уведомления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteka.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Очередь на книгу',
                'verbose_name_plural': 'Очереди на книги',
                'unique_together': {('user', 'book', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.book', verbose_name='Книга')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория книги',
                'verbose_name_plural': 'Категории книг',
                'unique_together': {('book', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LibrarianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_books', models.BooleanField(default=False, verbose_name='Может управлять книгами')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Может управлять пользователями')),
                ('can_manage_bookings', models.BooleanField(default=False, verbose_name='Может управлять бронированиями')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.branch', verbose_name='Филиал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Библиотекарь')),
            ],
            options={
                'verbose_name': 'Назначение библиотекаря',
                'verbose_name_plural': 'Назначения библиотекарей',
                'unique_together': {('user', 'branch')},
            },
        ),
    ]
