# Generated by Django 5.2.6 on 2025-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='inventory_number',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book_count',
            field=models.CharField(default=1, max_length=50, verbose_name='Количество книг'),
        ),
    ]
