# Generated by Django 5.2.6 on 2025-09-08 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_remove_bookcopy_inventory_number_bookcopy_book_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatbooking',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readingroom',
            name='floor',
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('seats_count', models.IntegerField(default=1, verbose_name='Количество мест')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.readingroom', verbose_name='Зал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование места',
                'verbose_name_plural': 'Бронирования мест',
            },
        ),
        migrations.DeleteModel(
            name='RoomSeat',
        ),
        migrations.DeleteModel(
            name='SeatBooking',
        ),
    ]
