# Generated by Django 5.2.6 on 2025-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0003_remove_seatbooking_seat_remove_seatbooking_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок возврата'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('returned', 'Возвращена'), ('overdue', 'Просрочена'), ('lost', 'Утеряна')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
