# Generated by Django 5.2.6 on 2025-09-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_bookcopy_return_date_alter_bookcopy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
