# Generated by Django 5.2.6 on 2025-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0005_remove_book_publisher_delete_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterUniqueTogether(
            name='roombooking',
            unique_together={('room', 'booking_date', 'start_time', 'end_time')},
        ),
    ]
