# Generated by Django 5.2.6 on 2025-12-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0006_book_price_alter_roombooking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookloan',
            name='is_overdue',
        ),
        migrations.AddField(
            model_name='bookloan',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('returned', 'Возвращена'), ('overdue', 'Просрочена'), ('lost', 'Утеряна'), ('fine_paid', 'Штраф оплачен')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='fine',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа в ЮKassa'),
        ),
        migrations.AddField(
            model_name='fine',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа в ЮKassa'),
        ),
    ]
