# Generated by Django 5.2.6 on 2025-12-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0007_remove_bookloan_is_overdue_bookloan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book_count',
            field=models.IntegerField(default=1, verbose_name='Количество книг'),
        ),
    ]
